version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sector-staff-postgres
    environment:
      POSTGRES_DB: sector_staff_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sector-staff-network

  redis:
    image: redis:7-alpine
    container_name: sector-staff-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sector-staff-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: sector-staff-app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=docker
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sector_staff_v2
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - sector-staff-network
    restart: unless-stopped

  # minio:
  #   image: minio/minio:latest
  #   container_name: sector-staff-minio
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio_data:/data
  #   command: server /data --console-address ":9001"
  #   networks:
  #     - sector-staff-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  sector-staff-network:
    driver: bridge