services:
  postgres:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-postgres-${ENVIRONMENT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main-network
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3
      disable: false

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis-${ENVIRONMENT}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - main-network
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      disable: false

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    container_name: ${COMPOSE_PROJECT_NAME}-app-${ENVIRONMENT}
    ports:
      - "${APP_PORT}:3000" 
    environment:
      NODE_ENV: ${ENVIRONMENT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: 3000
      # Add other environment variables as needed
    volumes:
      - .:/app:cached
      - node_modules_volume:/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - main-network
    init: true
    restart: unless-stopped

volumes:
  postgres_data:
    name: ${COMPOSE_PROJECT_NAME}_postgres_data_${ENVIRONMENT}
  redis_data:
    name: ${COMPOSE_PROJECT_NAME}_redis_data_${ENVIRONMENT}
  node_modules_volume:

networks:
  main-network:
    name: ${COMPOSE_PROJECT_NAME}_network_${ENVIRONMENT}